### ISSUE TITLE
Plugin "netlify-plugin-no-more-404" internal error

### ISSUE THREAD

**Issue by Arjun-chaurasiya** [sw-yx/netlify-plugin-no-more-404#13] opened 2020-07-24 13:58 UTC
Error message:ENOENT: no such file or directory, scandir '/opt/build/repo/opt/build/repo'
Error location:In "onPostBuild" event in "netlify-plugin-no-more-404" from netlify.toml

**Comment by ehmicky** [comment] 2020-07-24 18:14
Hi @Arjun-chaurasiya,
This is a duplicate of #4.

**Closed by ehmicky** 2020-07-24 18:14 UTC
